jukeBox/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.i18n import i18n_patterns
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('jukeBoxApp.urls')),
]

urlpatterns += i18n_patterns(
    path('i18n/', include('django.conf.urls.i18n')),
    path('', include('jukeBoxApp.urls')),
    prefix_default_language=False,
)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

jukeBoxApp/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('bandas/', views.BandaListView.as_view(), name='banda_lista'),
    path('banda/<int:pk>/', views.BandaDetailView.as_view(), name='banda_detalle'),
    path('estilos/', views.EstiloListView.as_view(), name='estilo_lista'),
    path('estilo/<int:pk>/', views.EstiloDetailView.as_view(), name='estilo_detalle'),
    path('paises/', views.PaisListView.as_view(), name='pais_lista'),
    path('cancion/<int:pk>/', views.CancionDetailView.as_view(), name='cancion_detalle'),
    path('sugerir/', views.SugerirCancionView.as_view(), name='sugerir_cancion'),
    path('pais/<int:pk>/', views.PaisDetailView.as_view(), name='pais_detalle'),
    path('favoritos/', views.FavoritosView.as_view(), name='favoritos'),
    path('api/canciones-favoritos/', views.ApiCancionesFavoritosView.as_view(), name='api_canciones_favoritos'),
    path('api/bandas/', views.ApiBandasView.as_view(), name='api_bandas'),
    path('api/favoritos/', views.ApiFavoritosView.as_view(), name='api_favoritos'),
    path('api/favoritos/sincronizar/', views.ApiSincronizarFavoritosView.as_view(), name='api_sincronizar_favoritos'),
]

jukeBoxApp/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Pais(models.Model):
    nombre = models.CharField(max_length=100)
    codigo = models.CharField(max_length=3)
    imagen = models.ImageField(upload_to='pais/', blank=True, null=True)
    
    def __str__(self):
        return self.nombre

class EstiloMusical(models.Model):
    nombre = models.CharField(max_length=50)
    descripcion = models.TextField()
    imagen = models.ImageField(upload_to='estilos/', blank=True, null=True)
    
    def __str__(self):
        return self.nombre

class Banda(models.Model):
    nombre = models.CharField(max_length=200)
    pais_origen = models.ForeignKey(Pais, on_delete=models.CASCADE)
    estilos = models.ManyToManyField(EstiloMusical)
    anio_formacion = models.IntegerField()
    descripcion = models.TextField()
    imagen = models.ImageField(upload_to='bandas/', blank=True, null=True)
    
    def __str__(self):
        return self.nombre

class Cancion(models.Model):
    titulo = models.CharField(max_length=200)
    banda = models.ForeignKey(Banda, on_delete=models.CASCADE, related_name='canciones')
    anio_publicacion = models.IntegerField()
    archivo_audio = models.FileField(upload_to='canciones/', blank=True, null=True)
    
    def __str__(self):
        return f"{self.titulo} - {self.banda.nombre}"
    
    class Meta:
        verbose_name = "Canción"
        verbose_name_plural = "Canciones"
        ordering = ['anio_publicacion']


class Valoracion(models.Model):
    RATING_CHOICES = [(i, str(i)) for i in range(1, 6)]
    cancion = models.ForeignKey(Cancion, on_delete=models.CASCADE, related_name='valoraciones')
    puntuacion = models.IntegerField(choices=RATING_CHOICES)
    comentario = models.TextField(blank=True)
    creado = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Valoración {self.puntuacion} - {self.cancion.titulo}"


class Sugerencia(models.Model):
    titulo = models.CharField(max_length=250)
    artista = models.CharField(max_length=200, blank=True)
    enlace = models.URLField(blank=True)
    comentario = models.TextField(blank=True)
    creado = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Sugerencia: {self.titulo} ({self.artista})"


class Favorito(models.Model):
    """
    Modelo para gestionar favoritos de bandas por usuario.
    Permite sincronización entre dispositivos y persistencia en backend.
    """
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='favoritos')
    banda = models.ForeignKey(Banda, on_delete=models.CASCADE, related_name='favoritos')
    creado = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = "Favorito"
        verbose_name_plural = "Favoritos"
        # Evitar duplicados: un usuario no puede tener la misma banda como favorito dos veces
        unique_together = ('user', 'banda')
        ordering = ['-creado']

    def __str__(self):
        return f"{self.user.username} - {self.banda.nombre}"

jukeBoxApp/forms.py
from django import forms
from .models import Valoracion, Sugerencia, Banda


class ValoracionForm(forms.ModelForm):
    class Meta:
        model = Valoracion
        fields = ['puntuacion', 'comentario']
        widgets = {
            'puntuacion': forms.RadioSelect(choices=Valoracion.RATING_CHOICES),
            'comentario': forms.Textarea(attrs={'class': 'form-control', 'rows': 3, 'placeholder': 'Deja tu comentario...'}),
        }


class SugerenciaForm(forms.ModelForm):
    # Campo personalizado para seleccionar artista existente o "Otro"
    ARTISTA_CHOICES = [('', '-- Seleccionar artista --')] + \
                     [(banda.nombre, banda.nombre) for banda in Banda.objects.all().order_by('nombre')] + \
                     [('otro', 'Otro artista')]

    artista_selector = forms.ChoiceField(
        choices=ARTISTA_CHOICES,
        required=False,
        widget=forms.Select(attrs={
            'class': 'form-control',
            'id': 'id_artista_selector'
        }),
        label="Artista"
    )

    # Campo adicional para escribir el nombre del artista cuando se selecciona "Otro"
    artista_otro = forms.CharField(
        required=False,
        max_length=200,
        widget=forms.TextInput(attrs={
            'class': 'form-control',
            'placeholder': 'Nombre del artista',
            'id': 'id_artista_otro'
        }),
        label=""
    )

    class Meta:
        model = Sugerencia
        fields = ['titulo', 'enlace', 'comentario']
        # Nota: artista_selector y artista_otro son campos adicionales no basados en modelo

    def save(self, commit=True):
        instance = super().save(commit=False)
        # El campo artista ya fue establecido en clean()
        instance.artista = self.cleaned_data.get('artista', '')
        if commit:
            instance.save()
        return instance

    def clean(self):
        cleaned_data = super().clean()
        artista_selector = cleaned_data.get('artista_selector')
        artista_otro = cleaned_data.get('artista_otro')

        if artista_selector == 'otro':
            if not artista_otro:
                raise forms.ValidationError("Debes especificar el nombre del artista.")
            cleaned_data['artista'] = artista_otro
        else:
            cleaned_data['artista'] = artista_selector

        return cleaned_data

jukeBoxApp/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse
from django.http import JsonResponse
from django.views.generic import TemplateView, ListView, DetailView, FormView, View
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.decorators.http import require_http_methods
from django.utils.decorators import method_decorator
from django.views.decorators.csrf import csrf_exempt
from .models import Banda, EstiloMusical, Pais, Cancion, Valoracion, Sugerencia, Favorito
from .forms import ValoracionForm, SugerenciaForm

# Create your views here.

class IndexView(TemplateView):
    template_name = 'jukeBoxApp/index.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # Obtener una banda por país
        paises = Pais.objects.all()
        bandas_destacadas = []
        for pais in paises:
            banda = Banda.objects.filter(pais_origen=pais).first()
            if banda:
                bandas_destacadas.append(banda)

        context['bandas_destacadas'] = bandas_destacadas
        return context

class BandaListView(ListView):
    model = Banda
    template_name = 'jukeBoxApp/banda_lista.html'
    context_object_name = 'bandas'
    
    def get_queryset(self):
        # Render first 12 bands on initial load, infinite scroll will load more
        return Banda.objects.all().order_by('nombre')[:12]

class BandaDetailView(DetailView):
    model = Banda
    template_name = 'jukeBoxApp/banda_detalle.html'
    context_object_name = 'banda'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['canciones'] = self.object.canciones.all()[:3]  # Obtener las 3 canciones de la banda
        return context

class EstiloListView(ListView):
    model = EstiloMusical
    template_name = 'jukeBoxApp/estilo_lista.html'
    context_object_name = 'estilos'

class EstiloDetailView(DetailView):
    model = EstiloMusical
    template_name = 'jukeBoxApp/estilo_detalle.html'
    context_object_name = 'estilo'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['estilos_relacionados'] = EstiloMusical.objects.exclude(pk=self.object.pk)[:5]

        # Obtener bandas que tienen este estilo
        bandas_con_estilo = self.object.banda_set.all()

        # Obtener canciones de estas bandas de forma aleatoria
        context['canciones'] = Cancion.objects.filter(banda__in=bandas_con_estilo).order_by('?')[:3]
        return context

class PaisListView(ListView):
    model = Pais
    template_name = 'jukeBoxApp/pais_lista.html'
    context_object_name = 'paises'

class PaisDetailView(DetailView):
    model = Pais
    template_name = 'jukeBoxApp/pais_detalle.html'
    context_object_name = 'pais'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['paises_relacionados'] = Pais.objects.exclude(pk=self.object.pk)[:5]

        # Obtener bandas de este país
        bandas_del_pais = self.object.banda_set.all()

        # Obtener canciones de estas bandas de forma aleatoria
        context['canciones'] = Cancion.objects.filter(banda__in=bandas_del_pais).order_by('?')[:3]
        return context

class FavoritosView(TemplateView):
    template_name = 'jukeBoxApp/favoritos.html'
    # La página de favoritos se maneja completamente con JavaScript y localStorage
    # Esta vista solo renderiza la plantilla


class CancionDetailView(DetailView):
    model = Cancion
    template_name = 'jukeBoxApp/cancion_detalle.html'
    context_object_name = 'cancion'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['valoraciones'] = self.object.valoraciones.order_by('-creado')

        # Calcular media de puntuaciones
        puntuaciones = self.object.valoraciones.all().values_list('puntuacion', flat=True)
        promedio = None
        if puntuaciones:
            promedio = round(sum(puntuaciones) / len(puntuaciones), 2)
        context['promedio'] = promedio
        context['form'] = ValoracionForm()
        return context

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        form = ValoracionForm(request.POST)
        if form.is_valid():
            valor = form.save(commit=False)
            valor.cancion = self.object
            valor.save()
            return redirect('cancion_detalle', pk=self.object.pk)

        context = self.get_context_data()
        context['form'] = form
        return self.render_to_response(context)


class SugerirCancionView(FormView):
    template_name = 'jukeBoxApp/sugerir_cancion.html'
    form_class = SugerenciaForm
    success_url = '/sugerir/'  # This will redirect to the same page

    def form_valid(self, form):
        form.save()
        return super().form_valid(form)

class ApiCancionesFavoritosView(View):
    # API para obtener canciones de bandas favoritas

    def get(self, request):
        ids = request.GET.get('ids', '')

        if not ids:
            return JsonResponse({'canciones': []})

        try:
            # Convertir IDs a lista de enteros
            banda_ids = [int(id.strip()) for id in ids.split(',') if id.strip()]

            # Obtener canciones de esas bandas
            canciones = Cancion.objects.filter(
                banda__id__in=banda_ids,
                archivo_audio__isnull=False
            ).select_related('banda')[:50]  # Límite de 50 canciones

            # Convertir a formato JSON
            canciones_data = []
            for cancion in canciones:
                canciones_data.append({
                    'titulo': cancion.titulo,
                    'banda': cancion.banda.nombre,
                    'imagen': cancion.banda.imagen.url if cancion.banda.imagen else '',
                    'archivo': cancion.archivo_audio.url if cancion.archivo_audio else '',
                    'duracion': '3:45'  # Podrías calcular esto del archivo
                })

            return JsonResponse(canciones_data, safe=False)

        except Exception as e:
            return JsonResponse({'error': str(e)}, status=400)


class ApiBandasView(View):
    """API que devuelve bandas paginadas en JSON para infinite scroll."""
    def get(self, request):
        try:
            page = int(request.GET.get('page', 1))
            page_size = int(request.GET.get('page_size', 6))
        except ValueError:
            return JsonResponse({'bands': [], 'has_more': False})

        filter_q = request.GET.get('filter', '')

        qs = Banda.objects.select_related('pais_origen').all().order_by('nombre')
        if filter_q and filter_q != '*':
            if filter_q == 'number':
                qs = qs.filter(nombre__regex=r'^[0-9]')
            else:
                qs = qs.filter(nombre__istartswith=filter_q)

        # Simple pagination
        start = (page - 1) * page_size
        end = start + page_size
        total = qs.count()
        items = qs[start:end]

        bands = []
        for b in items:
            rel_url = reverse('banda_detalle', args=[b.id])
            bands.append({
                'id': b.id,
                'nombre': b.nombre,
                'pais': b.pais_origen.nombre if b.pais_origen else '',
                'imagen': b.imagen.url if b.imagen else '',
                'url': rel_url
            })

        has_more = end < total

        return JsonResponse({'bands': bands, 'has_more': has_more})


class ApiFavoritosView(View):
    """
    API para gestionar favoritos de usuarios autenticados.
    GET: Lista favoritos del usuario
    POST: Añade/quita favorito (toggle)
    """
    
    def get(self, request):
        """Obtener lista de favoritos del usuario autenticado"""
        if not request.user.is_authenticated:
            return JsonResponse({'error': 'Usuario no autenticado'}, status=401)
        
        favoritos = Favorito.objects.filter(user=request.user).select_related('banda', 'banda__pais_origen')
        
        favoritos_data = []
        for fav in favoritos:
            banda = fav.banda
            favoritos_data.append({
                'id': banda.id,
                'nombre': banda.nombre,
                'pais': banda.pais_origen.nombre if banda.pais_origen else '',
                'imagen': banda.imagen.url if banda.imagen else '',
                'url': reverse('banda_detalle', args=[banda.id])
            })
        
        return JsonResponse(favoritos_data, safe=False)
    
    def post(self, request):
        """Toggle favorito (añadir o quitar)"""
        if not request.user.is_authenticated:
            return JsonResponse({'error': 'Usuario no autenticado'}, status=401)
        
        try:
            import json
            data = json.loads(request.body)
            banda_id = data.get('banda_id')
            
            if not banda_id:
                return JsonResponse({'error': 'banda_id requerido'}, status=400)
            
            banda = get_object_or_404(Banda, id=banda_id)
            
            # Intentar obtener el favorito existente
            favorito, created = Favorito.objects.get_or_create(
                user=request.user,
                banda=banda
            )
            
            if created:
                # Se creó (añadió a favoritos)
                return JsonResponse({
                    'action': 'added',
                    'message': 'Banda añadida a favoritos',
                    'banda': {
                        'id': banda.id,
                        'nombre': banda.nombre,
                        'pais': banda.pais_origen.nombre if banda.pais_origen else '',
                        'imagen': banda.imagen.url if banda.imagen else '',
                        'url': reverse('banda_detalle', args=[banda.id])
                    }
                })
            else:

jukeBoxApp/templates/jukeBoxApp/cancion_detalle.html
{% extends "jukeBoxApp/base.html" %}
{% load static %}
{% load i18n %}

{% block breadcumb_title %}{{ cancion.titulo }}{% endblock %}
{% block breadcumb_subtitle %}{% trans "Ficha de la canción" %}{% endblock %}
{% block breadcumb_style %}background-image: url({% static 'img/bg-img/breadcumb3.jpg' %});{% endblock %}

{% block content %}
<div class="container section-padding-100">
    <div class="row">
        <div class="col-12 col-lg-8">
            <h2>{{ cancion.titulo }}</h2>
            <p><strong>{% trans "Banda:" %}</strong> <a href="{% url 'banda_detalle' cancion.banda.id %}">{{ cancion.banda.nombre }}</a></p>
            <p><strong>{% trans "Año:" %}</strong> {{ cancion.anio_publicacion }}</p>

            {% if cancion.archivo_audio %}
            <audio controls style="width:100%;">
                <source src="{{ cancion.archivo_audio.url }}">
            </audio>
            {% endif %}

            
            <h4>{% trans "Deja tu valoración" %}</h4>
            <!-- Load CSS for rating -->
            <link rel="stylesheet" href="{% static 'css/valoracion.css' %}">

            <form method="post" id="valoracion-form">
                {% csrf_token %}
                <!-- Hidden input that will hold the numeric rating (1-5) -->
                <input type="hidden" name="puntuacion" id="id_puntuacion" value="">

                <!-- Star rating UI -->
                <div id="star-rating" class="mb-2" aria-label="{% trans 'Valoración' %}">
                    <i class="fa fa-star-o star" data-value="1" aria-hidden="true"></i>
                    <i class="fa fa-star-o star" data-value="2" aria-hidden="true"></i>
                    <i class="fa fa-star-o star" data-value="3" aria-hidden="true"></i>
                    <i class="fa fa-star-o star" data-value="4" aria-hidden="true"></i>
                    <i class="fa fa-star-o star" data-value="5" aria-hidden="true"></i>
                </div>

                <h4>{% trans "Déjanos tu opinión" %}</h4>

                <div class="form-group mt-2">
                    {{ form.comentario }}
                </div>
                <button type="submit" class="btn btn-primary">{% trans "Enviar valoración" %}</button>
            </form>

            <!-- Load JS for rating interaction -->
            <script src="{% static 'js/valoracion.js' %}"></script>

            <hr>

            <h4>{% trans "Valoraciones" %}</h4>
            {% if promedio %}
                <p>{% trans "Media:" %} {{ promedio }} / 5</p>
            {% endif %}

            {% if valoraciones %}
                <ul class="list-unstyled">
                {% for v in valoraciones %}
                    <li class="mb-3">
                        <strong>{{ v.puntuacion }} / 5</strong> — <small>{{ v.creado|date:"Y-m-d H:i" }}</small>
                        <p>{{ v.comentario|linebreaksbr }}</p>
                    </li>
                {% endfor %}
                </ul>
            {% else %}
                <p>{% trans "No hay valoraciones aún. Sé el primero en opinar." %}</p>
            {% endif %}

            <hr>

            <script>
                (function(){
                    const stars = document.querySelectorAll('#star-rating .star');
                    const input = document.getElementById('id_puntuacion');
                    let selected = 0;

                    function setVisual(value){
                        stars.forEach((s)=>{
                            const v = parseInt(s.getAttribute('data-value'));
                            if(v <= value){
                                s.classList.add('filled');
                                s.classList.remove('empty');
                            } else {
                                s.classList.add('empty');
                                s.classList.remove('filled');
                            }
                        });
                    }

                    stars.forEach((star)=>{
                        star.addEventListener('mouseover', function(){
                            const v = parseInt(this.getAttribute('data-value'));
                            setVisual(v);
                            this.classList.add('hovered');
                        });
                        star.addEventListener('mouseout', function(){
                            this.classList.remove('hovered');
                            setVisual(selected);
                        });
                        star.addEventListener('click', function(){
                            selected = parseInt(this.getAttribute('data-value'));
                            input.value = selected;
                            setVisual(selected);
                        });
                    });

                    // Initialize as empty
                    setVisual(0);

                    // Validate before submit
                    const form = document.getElementById('valoracion-form');
                    form.addEventListener('submit', function(e){
                        if(!input.value || parseInt(input.value) < 1){
                            e.preventDefault();
                            alert('{% trans "Por favor selecciona una puntuación (1-5 estrellas) antes de enviar." %}');
                        }
                    });
                })();
            </script>
        </div>

        <div class="col-12 col-lg-4">
            <div class="card mb-3">
                <div class="card-body">
                    <h5>{% trans "Sugerir una canción" %}</h5>
                    <p>{% trans "¿Tienes una canción para proponer?" %} <a href="{% url 'sugerir_cancion' %}">{% trans "Hazla llegar aquí" %}</a>.</p>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

jukeBoxApp/templates/jukeBoxApp/estilo_lista.html
{% extends "jukeBoxApp/base.html" %}
{% load static %}
{% load i18n %}

{% block breadcumb_title %}{% trans "Estilos Musicales" %}{% endblock %}
{% block breadcumb_subtitle %}{% trans "Explora los estilos" %}{% endblock %}
{% block breadcumb_style %}background-image: url({% static 'img/bg-img/breadcumb3.jpg' %});{% endblock %}

{% block content %}
<!-- ##### Blog Area Start ##### -->
<div class="blog-area section-padding-100">
    <div class="container">
        <div class="row">
            <div class="col-12 col-lg-9">
                {% for estilo in estilos %}
                <!-- Single Post Start -->
                <div id="estilo-{{ estilo.id }}" class="single-blog-post mb-100 wow fadeInUp" data-wow-delay="100ms">
                    <!-- Post Thumb -->
                    <div class="blog-post-thumb mt-30">
                        <a href="{% url 'estilo_detalle' estilo.id %}">
                            {% if estilo.imagen %}
                                <img src="{{ estilo.imagen.url }}" alt="{{ estilo.nombre }}">
                            {% else %}
                                <img src="{% static 'img/bg-img/blog1.jpg' %}" alt="{{ estilo.nombre }}">
                            {% endif %}
                        </a>
                        <!-- Post Date -->
                        <div class="post-date">
                            <span>{{ forloop.counter }}</span>
                            <span>{% trans "Estilo" %}</span>
                        </div>
                    </div>

                    <!-- Blog Content -->
                    <div class="blog-content">
                        <!-- Post Title -->
                        <a href="{% url 'estilo_detalle' estilo.id %}" class="post-title">{{ estilo.nombre }}</a>
                        <!-- Post Meta -->
                        <div class="post-meta d-flex mb-30">
                            <p class="post-author">{% trans "Género Musical" %}</p>
                            <p class="tags">
                                {% blocktrans trimmed count band_count=estilo.banda_set.count %}
                                {{ band_count }} banda
                                {% plural %}
                                {{ band_count }} bandas
                                {% endblocktrans %}
                                </p>
                        </div>
                        <!-- Post Excerpt -->
                        
                        <p>
                            {% if estilo.descripcion %}
                                {{ estilo.descripcion }}
                            {% else %}
                                {% trans "Descubre las bandas de este estilo musical. Explora la diversidad y riqueza de este género que ha marcado la historia de la música." %}
                            {% endif %}
                        </p>
                    </div>
                </div>
                {% endfor %}
            </div>

            <div class="col-12 col-lg-3">
                <div class="blog-sidebar-area">

                    <!-- Widget Area - Todos los Estilos -->
                    <div class="single-widget-area mb-30">
                        <div class="widget-title">
                            <h5>{% trans "Todos los Estilos" %}</h5>
                        </div>
                        <div class="widget-content">
                            <ul>
                                {% for estilo in estilos %}
                                <li><a href="#estilo-{{ estilo.id }}">{{ estilo.nombre }} ({{ estilo.banda_set.count }})</a></li>
                                {% endfor %}
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- ##### Blog Area End ##### -->
{% endblock %}

jukeBoxApp/templates/jukeBoxApp/sugerir_cancion.html
{% extends "jukeBoxApp/base.html" %}
{% load static %}
{% load i18n %}

{% block breadcumb_title %}{% trans "Sugerir Canción" %}{% endblock %}
{% block breadcumb_subtitle %}{% trans "Propon una canción para el catálogo" %}{% endblock %}
{% block breadcumb_style %}background-image: url({% static 'img/bg-img/breadcumb3.jpg' %});{% endblock %}

{% block content %}
<div class="container section-padding-100">
    <div class="row justify-content-center">
        <div class="col-12 col-md-8">
            <div class="card">
                <div class="card-body">
                    <h4 class="card-title">{% trans "Sugerir Canción" %}</h4>
                    <form method="post">
                        {% csrf_token %}

                        <div class="mb-3">
                            <strong>Título:</strong><br>
                            {{ form.titulo }}
                            {% for error in form.titulo.errors %}
                            <div class="text-danger">{{ error }}</div>
                            {% endfor %}
                        </div>

                        <div class="mb-3">
                            <strong>Artista:</strong><br>
                            {{ form.artista_selector }}
                            {% for error in form.artista_selector.errors %}
                            <div class="text-danger">{{ error }}</div>
                            {% endfor %}
                        </div>

                        <div class="mb-3 artista-otro-container" id="artista-otro-container">
                            <strong>Nombre del artista:</strong><br>
                            {{ form.artista_otro }}
                            {% for error in form.artista_otro.errors %}
                            <div class="text-danger">{{ error }}</div>
                            {% endfor %}
                        </div>

                        <div class="mb-3">
                            <strong>Enlace:</strong><br>
                            {{ form.enlace }}
                        </div>

                        <div class="mb-3">
                            <strong>Comentario:</strong><br>
                            {{ form.comentario }}
                        </div>
                        <button type="submit" class="btn btn-success">{% trans "Enviar sugerencia" %}</button>
                    </form>
                    <hr>
                    <p class="small text-muted mt-3">{% trans "Las sugerencias serán revisadas manualmente." %}</p>
                </div>
            </div>
        </div>
    </div>
</div>

<script>
    // Función para mostrar/ocultar el campo de artista personalizado
    function toggleArtistaOtro() {
        var selector = document.getElementById('id_artista_selector');
        var container = document.getElementById('artista-otro-container');
        var input = document.getElementById('id_artista_otro');

        if (selector && container && input) {
            if (selector.value === 'otro') {
                container.style.display = 'block';
                input.required = true;
            } else {
                container.style.display = 'none';
                input.required = false;
                input.value = '';
            }
        }
    }

    // Usar jQuery si está disponible, sino vanilla JS
    if (typeof jQuery !== 'undefined') {
        $(document).ready(function () {
            $('#id_artista_selector').change(toggleArtistaOtro);
            toggleArtistaOtro(); // Estado inicial

            // Add form-control class to other fields to match width
            $('#id_titulo, #id_enlace, #id_comentario, #id_artista_otro').addClass('form-control');
        });
    } else {
        // Vanilla JS fallback
        document.addEventListener('DOMContentLoaded', function () {
            var selector = document.getElementById('id_artista_selector');
            if (selector) {
                selector.addEventListener('change', toggleArtistaOtro);
                toggleArtistaOtro(); // Estado inicial
            }

            // Add form-control class to other fields to match width
            var fields = ['id_titulo', 'id_enlace', 'id_comentario', 'id_artista_otro'];
            fields.forEach(function (id) {
                var element = document.getElementById(id);
                if (element) {
                    element.classList.add('form-control');
                }
            });
        });
    }
</script>
{% endblock %}